export const sceneCategories = [
  { value: "all", label: "全部" },
  { value: "clothing", label: "购物消费" },
  { value: "dining", label: "餐饮沟通" },
  { value: "housing", label: "居住生活" },
  { value: "transport", label: "旅行出行" },
  { value: "work", label: "职场沟通" },
  { value: "social", label: "社交关系" },
  { value: "health", label: "健康医疗" },
  { value: "services", label: "公共服务" },
  { value: "learning", label: "校园学习" },
  { value: "emergency", label: "紧急求助" },
] as const

export const sceneLevels = [
  { value: "all", label: "全部等级" },
  { value: "A2", label: "A2" },
  { value: "B1", label: "B1" },
  { value: "B2", label: "B2" },
  { value: "C1", label: "C1" },
] as const

export type SceneCategory = Exclude<(typeof sceneCategories)[number]["value"], "all">
export type SceneLevel = Exclude<(typeof sceneLevels)[number]["value"], "all">
export type SceneStatus = "active" | "mastered" | "locked"

export type SceneItem = {
  id: string
  title: string
  englishTitle: string
  description: string
  category: SceneCategory
  tags: string[]
  level: SceneLevel
  progress: number
  duration: number
  status: SceneStatus
  vocabulary: string[]
}

const coreSceneItems: SceneItem[] = [
  {
    id: "coffee",
    title: "咖啡店点单",
    englishTitle: "Ordering at a café",
    description: "礼貌点单、调整饮品要求并完成结账。",
    category: "dining",
    tags: ["饮品定制", "柜台点单", "结账确认"],
    level: "A2",
    progress: 72,
    duration: 18,
    status: "active",
    vocabulary: ["decaf", "to go", "oat milk"],
  },
  {
    id: "small-talk",
    title: "日常寒暄",
    englishTitle: "Everyday small talk",
    description: "自然开启对话、延续话题并礼貌结束。",
    category: "social",
    tags: ["熟人偶遇", "延续话题", "礼貌告别"],
    level: "A2",
    progress: 100,
    duration: 26,
    status: "mastered",
    vocabulary: ["catch up", "lately", "sounds good"],
  },
  {
    id: "meeting",
    title: "工作会议",
    englishTitle: "Speaking in meetings",
    description: "表达观点、澄清信息并推进讨论。",
    category: "work",
    tags: ["观点表达", "澄清分歧", "行动确认"],
    level: "B1",
    progress: 46,
    duration: 34,
    status: "active",
    vocabulary: ["clarify", "trade-off", "follow up"],
  },
  {
    id: "idiomatic-english",
    title: "生活与职场地道表达",
    englishTitle: "Idiomatic English in context",
    description: "在连续对话中理解并复用高频地道词组，掌握含义、隐喻和真实语域。",
    category: "work",
    tags: ["日常口语", "职场表达", "词源理解"],
    level: "B2",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["keep tabs on", "on the same page", "circle back"],
  },
  {
    id: "airport",
    title: "机场出行",
    englishTitle: "At the airport",
    description: "办理值机、询问登机口和处理行李问题。",
    category: "transport",
    tags: ["值机办理", "行李托运", "登机问路"],
    level: "A2",
    progress: 35,
    duration: 12,
    status: "active",
    vocabulary: ["boarding pass", "aisle", "carry-on"],
  },
  {
    id: "restaurant",
    title: "餐厅用餐",
    englishTitle: "Dining out",
    description: "预订座位、询问菜品并反馈需求。",
    category: "dining",
    tags: ["菜品推荐", "饮食要求", "餐桌服务"],
    level: "A2",
    progress: 88,
    duration: 29,
    status: "active",
    vocabulary: ["reservation", "recommend", "allergy"],
  },
  {
    id: "shopping",
    title: "商店购物",
    englishTitle: "Shopping in store",
    description: "询问尺寸、比较商品并处理退换。",
    category: "clothing",
    tags: ["尺寸库存", "试穿比较", "退换规则"],
    level: "A2",
    progress: 20,
    duration: 9,
    status: "active",
    vocabulary: ["in stock", "fit", "receipt"],
  },
  {
    id: "hotel",
    title: "酒店入住",
    englishTitle: "Hotel check-in",
    description: "确认预订、提出房间需求并询问设施。",
    category: "housing",
    tags: ["预订核验", "房型偏好", "设施咨询"],
    level: "B1",
    progress: 12,
    duration: 6,
    status: "active",
    vocabulary: ["booking", "amenity", "checkout"],
  },
  {
    id: "doctor",
    title: "就医沟通",
    englishTitle: "At the doctor",
    description: "准确描述症状、时长和身体感受。",
    category: "health",
    tags: ["症状描述", "病程说明", "就诊问答"],
    level: "B1",
    progress: 8,
    duration: 4,
    status: "active",
    vocabulary: ["symptom", "sore", "prescription"],
  },
  {
    id: "presentation",
    title: "英文演讲",
    englishTitle: "Giving a presentation",
    description: "建立结构、引导听众并回应提问。",
    category: "work",
    tags: ["结构表达", "听众引导", "现场问答"],
    level: "B2",
    progress: 0,
    duration: 0,
    status: "locked",
    vocabulary: ["overview", "highlight", "takeaway"],
  },
  {
    id: "interview",
    title: "求职面试",
    englishTitle: "Job interview",
    description: "介绍经历、用案例说明能力并反问。",
    category: "work",
    tags: ["经历介绍", "案例表达", "岗位反问"],
    level: "B2",
    progress: 14,
    duration: 11,
    status: "active",
    vocabulary: ["strength", "challenge", "impact"],
  },
  {
    id: "grocery",
    title: "超市采购",
    englishTitle: "Grocery shopping",
    description: "寻找商品、确认价格并询问替代选择。",
    category: "dining",
    tags: ["货架问路", "价格确认", "替代商品"],
    level: "A2",
    progress: 24,
    duration: 10,
    status: "active",
    vocabulary: ["aisle", "on sale", "substitute"],
  },
  {
    id: "renting",
    title: "租房看房",
    englishTitle: "Viewing an apartment",
    description: "询问租金、设施、合同与入住条件。",
    category: "housing",
    tags: ["租金费用", "房屋设施", "合同条款"],
    level: "B1",
    progress: 18,
    duration: 13,
    status: "active",
    vocabulary: ["deposit", "utilities", "lease"],
  },
  {
    id: "taxi",
    title: "打车出行",
    englishTitle: "Taking a taxi",
    description: "说明目的地、确认路线并处理费用。",
    category: "transport",
    tags: ["目的地说明", "路线确认", "车费支付"],
    level: "A2",
    progress: 40,
    duration: 16,
    status: "active",
    vocabulary: ["drop off", "route", "fare"],
  },
  {
    id: "train",
    title: "火车换乘",
    englishTitle: "Taking a train",
    description: "购买车票、确认站台并处理换乘。",
    category: "transport",
    tags: ["车票购买", "站台确认", "换乘安排"],
    level: "A2",
    progress: 16,
    duration: 7,
    status: "active",
    vocabulary: ["platform", "transfer", "one-way"],
  },
  {
    id: "pharmacy",
    title: "药房购药",
    englishTitle: "At the pharmacy",
    description: "描述症状、询问用法并确认注意事项。",
    category: "health",
    tags: ["用药咨询", "剂量频次", "风险确认"],
    level: "B1",
    progress: 10,
    duration: 5,
    status: "active",
    vocabulary: ["dosage", "side effect", "over-the-counter"],
  },
  {
    id: "networking",
    title: "职场社交",
    englishTitle: "Professional networking",
    description: "自然自我介绍、了解对方并交换联系方式。",
    category: "social",
    tags: ["职业介绍", "建立联系", "后续跟进"],
    level: "B1",
    progress: 22,
    duration: 14,
    status: "active",
    vocabulary: ["industry", "role", "keep in touch"],
  },
  {
    id: "banking",
    title: "银行办事",
    englishTitle: "At the bank",
    description: "说明业务需求、核对材料并确认办理进度。",
    category: "services",
    tags: ["业务办理", "材料核对", "进度确认"],
    level: "B1",
    progress: 6,
    duration: 3,
    status: "active",
    vocabulary: ["account", "transfer", "statement"],
  },
  {
    id: "bakery",
    title: "面包店选购",
    englishTitle: "At the bakery",
    description: "询问口味与配料，选择数量并确认包装。",
    category: "dining",
    tags: ["口味询问", "数量表达", "打包需求"],
    level: "A2",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["freshly baked", "filling", "a dozen"],
  },
  {
    id: "customs",
    title: "海关入境",
    englishTitle: "Going through customs",
    description: "说明来访目的、停留时间与携带物品。",
    category: "transport",
    tags: ["入境问答", "行程说明", "物品申报"],
    level: "B1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["declare", "purpose", "accommodation"],
  },
  {
    id: "directions",
    title: "街头问路",
    englishTitle: "Asking for directions",
    description: "确认目的地位置，理解路线并核对步行时间。",
    category: "transport",
    tags: ["地点确认", "路线理解", "时间估算"],
    level: "A2",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["intersection", "across from", "on your left"],
  },
  {
    id: "home-repair",
    title: "联系房东报修",
    englishTitle: "Reporting a home repair",
    description: "说明故障、描述影响并协商上门时间。",
    category: "housing",
    tags: ["故障描述", "影响说明", "时间协调"],
    level: "B1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["leaking", "power outage", "appointment window"],
  },
  {
    id: "customer-support",
    title: "联系客服退款",
    englishTitle: "Requesting a refund",
    description: "解释订单问题、提出诉求并确认退款进度。",
    category: "services",
    tags: ["订单说明", "退款协商", "进度追踪"],
    level: "B1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["refund", "damaged", "reference number"],
  },
  {
    id: "emergency-help",
    title: "紧急情况求助",
    englishTitle: "Getting emergency help",
    description: "快速说明位置、现场情况和需要的帮助。",
    category: "emergency",
    tags: ["位置报告", "情况描述", "安全确认"],
    level: "B1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["emergency", "injured", "stay on the line"],
  },
  {
    id: "class-discussion",
    title: "课堂讨论",
    englishTitle: "Joining a class discussion",
    description: "回应观点、补充依据并礼貌表达不同意见。",
    category: "learning",
    tags: ["回应观点", "补充依据", "礼貌反驳"],
    level: "B1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["evidence", "in contrast", "build on"],
  },
  {
    id: "one-on-one",
    title: "一对一工作沟通",
    englishTitle: "A workplace one-on-one",
    description: "同步进展、提出阻碍并讨论所需支持。",
    category: "work",
    tags: ["进展同步", "阻碍说明", "支持请求"],
    level: "B2",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["priority", "blocked", "support"],
  },
  {
    id: "negotiation",
    title: "商务谈判",
    englishTitle: "Business negotiation",
    description: "界定核心利益、交换条件并推动双方形成共识。",
    category: "work",
    tags: ["利益澄清", "条件交换", "共识推进"],
    level: "C1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["concession", "bottom line", "mutual ground"],
  },
  {
    id: "panel-debate",
    title: "圆桌辩论",
    englishTitle: "Panel discussion",
    description: "提炼复杂立场、回应质疑并有分寸地反驳。",
    category: "learning",
    tags: ["立场提炼", "即时回应", "审慎反驳"],
    level: "C1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["nuance", "counterargument", "premise"],
  },
  {
    id: "crisis-briefing",
    title: "危机沟通",
    englishTitle: "Crisis briefing",
    description: "在信息不完整时同步事实、限定判断并协调行动。",
    category: "emergency",
    tags: ["事实同步", "风险限定", "行动协调"],
    level: "C1",
    progress: 0,
    duration: 0,
    status: "active",
    vocabulary: ["contingency", "verified", "escalation"],
  },
]

function createScene(
  id: string,
  title: string,
  englishTitle: string,
  description: string,
  category: SceneCategory,
  level: SceneLevel,
  tags: string[],
  vocabulary: string[],
): SceneItem {
  return {
    id,
    title,
    englishTitle,
    description,
    category,
    level,
    tags,
    vocabulary,
    progress: 0,
    duration: 0,
    status: "active",
  }
}

const expandedSceneItems: SceneItem[] = [
  createScene(
    "fitting-room",
    "试衣间沟通",
    "In the fitting room",
    "询问试衣间位置、调整尺码并表达穿着感受。",
    "clothing",
    "A2",
    ["寻找试衣间", "更换尺码", "描述合身度"],
    ["fitting room", "a size up", "too tight"],
  ),
  createScene(
    "shoe-store",
    "鞋店选购",
    "Buying shoes",
    "确认鞋码、试穿不同款式并比较舒适度。",
    "clothing",
    "A2",
    ["确认鞋码", "试穿款式", "比较舒适度"],
    ["shoe size", "try on", "comfortable"],
  ),
  createScene(
    "electronics-store",
    "数码产品选购",
    "Buying electronics",
    "比较产品功能、询问保修并确认退换条件。",
    "clothing",
    "B1",
    ["功能比较", "保修咨询", "退换确认"],
    ["warranty", "compatible", "return window"],
  ),
  createScene(
    "farmers-market",
    "市集采购",
    "At a farmers market",
    "询问产地与新鲜度，选择数量并协商价格。",
    "clothing",
    "A2",
    ["询问产地", "选择数量", "价格确认"],
    ["locally grown", "ripe", "per pound"],
  ),
  createScene(
    "online-order-pickup",
    "到店取货",
    "Picking up an order",
    "核对线上订单、处理缺件并完成到店取货。",
    "clothing",
    "B1",
    ["订单核验", "缺件说明", "取货确认"],
    ["pickup order", "order number", "missing item"],
  ),
  createScene(
    "food-delivery",
    "外卖配送沟通",
    "Food delivery",
    "说明配送位置、处理延误并核对餐品。",
    "dining",
    "A2",
    ["位置说明", "延误沟通", "餐品核对"],
    ["delivery", "entrance", "running late"],
  ),
  createScene(
    "brunch-reservation",
    "早午餐订位",
    "Booking brunch",
    "预约座位、确认人数并协调到店时间。",
    "dining",
    "A2",
    ["预约座位", "人数确认", "到店时间"],
    ["table for four", "available", "reservation"],
  ),
  createScene(
    "street-food",
    "街头小吃点单",
    "Ordering street food",
    "询问特色口味、辣度和方便携带的吃法。",
    "dining",
    "A2",
    ["特色询问", "辣度确认", "打包携带"],
    ["specialty", "spicy", "to go"],
  ),
  createScene(
    "dietary-needs",
    "说明饮食要求",
    "Explaining dietary needs",
    "清楚说明过敏、饮食限制并确认替代方案。",
    "dining",
    "B1",
    ["过敏说明", "配料核对", "替代方案"],
    ["allergic", "gluten-free", "substitute"],
  ),
  createScene(
    "dinner-party",
    "家庭聚餐",
    "At a dinner party",
    "赞美菜品、参与餐桌话题并礼貌回应招待。",
    "dining",
    "B1",
    ["赞美菜品", "参与话题", "回应招待"],
    ["delicious", "homemade", "help yourself"],
  ),
  createScene(
    "roommate-rules",
    "合租规则协商",
    "Setting roommate rules",
    "讨论清洁、作息和公共空间的使用规则。",
    "housing",
    "B1",
    ["清洁分工", "作息协商", "公共空间"],
    ["chore", "quiet hours", "shared space"],
  ),
  createScene(
    "utility-setup",
    "开通水电网络",
    "Setting up utilities",
    "提供住址信息、选择套餐并确认开通时间。",
    "housing",
    "B1",
    ["住址核验", "套餐选择", "开通时间"],
    ["utility", "billing cycle", "activation"],
  ),
  createScene(
    "moving-day",
    "搬家当日",
    "On moving day",
    "向搬运人员说明物品、楼层和摆放要求。",
    "housing",
    "A2",
    ["物品说明", "路线指引", "摆放要求"],
    ["fragile", "upstairs", "place it here"],
  ),
  createScene(
    "neighbor-noise",
    "邻里噪音沟通",
    "Talking about noise",
    "友善说明噪音影响并协商安静时段。",
    "housing",
    "B1",
    ["说明影响", "提出请求", "协商时段"],
    ["keep it down", "disturb", "quiet hours"],
  ),
  createScene(
    "furniture-delivery",
    "家具配送",
    "Furniture delivery",
    "核对配送时间、处理安装问题并检查损坏。",
    "housing",
    "B1",
    ["配送核对", "安装沟通", "损坏反馈"],
    ["delivery window", "assemble", "damaged"],
  ),
  createScene(
    "car-rental",
    "租车办理",
    "Renting a car",
    "选择车型、确认保险和车辆归还要求。",
    "transport",
    "B1",
    ["车型选择", "保险确认", "归还要求"],
    ["rental car", "coverage", "return full"],
  ),
  createScene(
    "bus-route",
    "公交路线咨询",
    "Taking the bus",
    "确认线路、上下车站点和支付方式。",
    "transport",
    "A2",
    ["线路确认", "站点询问", "票价支付"],
    ["bus stop", "get off", "fare"],
  ),
  createScene(
    "flight-delay",
    "航班延误处理",
    "Handling a flight delay",
    "了解延误原因、转机影响和改签选择。",
    "transport",
    "B1",
    ["原因询问", "转机影响", "改签选择"],
    ["delayed", "connection", "rebook"],
  ),
  createScene(
    "lost-luggage",
    "行李遗失申报",
    "Reporting lost luggage",
    "描述行李特征、提交信息并追踪处理进度。",
    "transport",
    "B1",
    ["行李描述", "信息登记", "进度追踪"],
    ["baggage claim", "missing", "tracking number"],
  ),
  createScene(
    "bike-rental",
    "租借自行车",
    "Renting a bicycle",
    "选择车型、了解计费并确认安全装备。",
    "transport",
    "A2",
    ["车型选择", "计费方式", "安全装备"],
    ["hourly rate", "helmet", "return station"],
  ),
  createScene(
    "road-trip",
    "自驾路线规划",
    "Planning a road trip",
    "讨论路线、休息站和突发天气备选方案。",
    "transport",
    "B2",
    ["路线比较", "休息安排", "备选方案"],
    ["scenic route", "rest stop", "detour"],
  ),
  createScene(
    "project-kickoff",
    "项目启动会",
    "Project kickoff",
    "对齐目标、角色和首个里程碑。",
    "work",
    "B1",
    ["目标对齐", "角色分工", "里程碑确认"],
    ["scope", "owner", "milestone"],
  ),
  createScene(
    "status-update",
    "项目进度汇报",
    "Giving a status update",
    "简洁汇报完成项、风险和下一步计划。",
    "work",
    "B1",
    ["完成项", "风险说明", "下一步计划"],
    ["on track", "risk", "next step"],
  ),
  createScene(
    "performance-review",
    "绩效沟通",
    "Performance review",
    "总结贡献、讨论反馈并设定成长目标。",
    "work",
    "B2",
    ["贡献总结", "反馈回应", "成长目标"],
    ["contribution", "feedback", "development goal"],
  ),
  createScene(
    "salary-negotiation",
    "薪酬协商",
    "Salary negotiation",
    "陈述价值依据、讨论薪酬范围并确认后续。",
    "work",
    "C1",
    ["价值陈述", "范围讨论", "后续确认"],
    ["compensation", "market rate", "total package"],
  ),
  createScene(
    "client-demo",
    "客户产品演示",
    "Client product demo",
    "引导产品演示、回应顾虑并确认试用计划。",
    "work",
    "B2",
    ["演示引导", "顾虑回应", "试用确认"],
    ["walk through", "use case", "trial"],
  ),
  createScene(
    "remote-collaboration",
    "远程协作",
    "Remote collaboration",
    "跨时区安排协作、澄清异步信息并确认责任。",
    "work",
    "B2",
    ["时区协调", "异步澄清", "责任确认"],
    ["time zone", "async", "handoff"],
  ),
  createScene(
    "conflict-resolution",
    "工作冲突调解",
    "Resolving workplace conflict",
    "描述分歧、倾听对方需求并达成可执行方案。",
    "work",
    "C1",
    ["分歧描述", "需求澄清", "方案共识"],
    ["misalignment", "concern", "resolution"],
  ),
  createScene(
    "making-plans",
    "朋友约见",
    "Making plans",
    "提出活动建议、协调时间并确认安排。",
    "social",
    "A2",
    ["提出建议", "协调时间", "确认安排"],
    ["free this weekend", "how about", "see you then"],
  ),
  createScene(
    "party-introduction",
    "聚会自我介绍",
    "Introducing yourself at a party",
    "自然加入谈话、介绍自己并记住对方信息。",
    "social",
    "A2",
    ["加入谈话", "自我介绍", "了解对方"],
    ["mind if I join", "nice to meet you", "how do you know"],
  ),
  createScene(
    "dating-conversation",
    "初次约会交流",
    "On a first date",
    "分享兴趣、提出开放问题并尊重个人边界。",
    "social",
    "B1",
    ["兴趣分享", "开放提问", "边界表达"],
    ["into", "what about you", "comfortable"],
  ),
  createScene(
    "community-event",
    "社区活动",
    "At a community event",
    "了解活动安排、主动帮忙并认识邻里。",
    "social",
    "B1",
    ["活动询问", "主动帮忙", "邻里交流"],
    ["volunteer", "schedule", "neighborhood"],
  ),
  createScene(
    "hosting-guests",
    "在家招待客人",
    "Hosting guests",
    "迎接客人、提供选择并照顾对方需要。",
    "social",
    "B1",
    ["迎接客人", "提供选择", "照顾需求"],
    ["make yourself at home", "would you like", "help yourself"],
  ),
  createScene(
    "dentist-visit",
    "牙科就诊",
    "At the dentist",
    "描述不适位置、了解治疗并确认术后注意事项。",
    "health",
    "B1",
    ["不适描述", "治疗询问", "术后确认"],
    ["sensitive", "filling", "aftercare"],
  ),
  createScene(
    "appointment-booking",
    "预约门诊",
    "Booking a medical appointment",
    "说明就诊需求、协调时间并核对保险信息。",
    "health",
    "A2",
    ["就诊需求", "时间协调", "信息核对"],
    ["appointment", "available slot", "insurance"],
  ),
  createScene(
    "health-insurance",
    "医疗保险咨询",
    "Understanding health insurance",
    "确认保障范围、自付费用和理赔流程。",
    "health",
    "B2",
    ["保障范围", "费用确认", "理赔流程"],
    ["coverage", "deductible", "claim"],
  ),
  createScene(
    "mental-wellness",
    "心理健康沟通",
    "Talking about mental wellness",
    "描述近期状态、压力来源和需要的支持。",
    "health",
    "B2",
    ["状态描述", "压力来源", "支持需求"],
    ["overwhelmed", "coping", "support"],
  ),
  createScene(
    "fitness-coaching",
    "健身指导",
    "With a fitness coach",
    "说明目标、身体限制并确认训练动作。",
    "health",
    "B1",
    ["目标说明", "限制说明", "动作确认"],
    ["fitness goal", "injury", "proper form"],
  ),
  createScene(
    "post-office",
    "邮局寄件",
    "At the post office",
    "选择寄送方式、填写地址并确认到达时间。",
    "services",
    "A2",
    ["寄送选择", "地址填写", "时效确认"],
    ["parcel", "tracking", "delivery time"],
  ),
  createScene(
    "phone-plan",
    "办理手机套餐",
    "Choosing a phone plan",
    "比较流量套餐、合约期限和额外费用。",
    "services",
    "B1",
    ["套餐比较", "合约确认", "费用询问"],
    ["data plan", "contract", "extra charge"],
  ),
  createScene(
    "internet-support",
    "网络故障报修",
    "Internet support",
    "描述连接问题、完成排查并预约技术支持。",
    "services",
    "B1",
    ["故障描述", "步骤排查", "预约支持"],
    ["connection", "router", "technician"],
  ),
  createScene(
    "library-card",
    "办理图书证",
    "Getting a library card",
    "了解申请材料、借阅规则和电子资源。",
    "services",
    "A2",
    ["材料确认", "借阅规则", "资源咨询"],
    ["proof of address", "renew", "digital access"],
  ),
  createScene(
    "government-office",
    "政务窗口办事",
    "At a government office",
    "说明办理事项、补充材料并确认处理周期。",
    "services",
    "B2",
    ["事项说明", "材料补充", "周期确认"],
    ["application", "supporting document", "processing time"],
  ),
  createScene(
    "office-hours",
    "教师答疑时间",
    "During office hours",
    "说明困惑、追问反馈并确认改进方向。",
    "learning",
    "B1",
    ["困惑说明", "反馈追问", "方向确认"],
    ["office hours", "struggling with", "improve"],
  ),
  createScene(
    "group-project",
    "小组项目协作",
    "Working on a group project",
    "分配任务、协调截止时间并解决协作问题。",
    "learning",
    "B1",
    ["任务分配", "截止时间", "协作问题"],
    ["assign", "deadline", "contribution"],
  ),
  createScene(
    "course-enrollment",
    "课程选课",
    "Enrolling in a course",
    "了解先修要求、候补名单和课程负担。",
    "learning",
    "B1",
    ["先修要求", "候补咨询", "负担评估"],
    ["prerequisite", "waitlist", "workload"],
  ),
  createScene(
    "exam-preparation",
    "备考计划",
    "Preparing for an exam",
    "确定重点、讨论复习方法并安排模拟练习。",
    "learning",
    "B2",
    ["重点确认", "方法讨论", "模拟安排"],
    ["review material", "practice test", "study strategy"],
  ),
  createScene(
    "study-abroad",
    "留学咨询",
    "Study abroad advising",
    "比较项目、准备申请并讨论文化适应。",
    "learning",
    "B2",
    ["项目比较", "申请准备", "文化适应"],
    ["program", "application", "culture shock"],
  ),
  createScene(
    "lost-phone",
    "手机遗失求助",
    "Reporting a lost phone",
    "说明遗失时间地点、描述设备并采取保护措施。",
    "emergency",
    "A2",
    ["时间地点", "设备描述", "账户保护"],
    ["lost", "last seen", "lock the device"],
  ),
  createScene(
    "report-theft",
    "报案说明失窃",
    "Reporting a theft",
    "按顺序陈述经过、提供物品信息并获取报案编号。",
    "emergency",
    "B1",
    ["经过陈述", "物品信息", "编号获取"],
    ["stolen", "description", "case number"],
  ),
  createScene(
    "car-breakdown",
    "车辆抛锚求助",
    "Handling a car breakdown",
    "报告位置与车辆状况，联系救援并确认等待时间。",
    "emergency",
    "B1",
    ["位置报告", "故障说明", "救援确认"],
    ["breakdown", "roadside assistance", "tow truck"],
  ),
  createScene(
    "missed-flight",
    "误机后改签",
    "After missing a flight",
    "解释误机原因、询问替代航班并处理住宿需求。",
    "emergency",
    "B1",
    ["原因说明", "航班替代", "住宿需求"],
    ["missed flight", "next available", "overnight stay"],
  ),
  createScene(
    "thrift-store",
    "二手店淘货",
    "Shopping at a thrift store",
    "询问商品状况、了解来源并确认折扣规则。",
    "clothing",
    "A2",
    ["商品状况", "来源询问", "折扣确认"],
    ["pre-owned", "condition", "discount"],
  ),
  createScene(
    "jewelry-store",
    "珠宝店选购",
    "Choosing jewelry",
    "描述款式偏好、比较材质并询问保养方式。",
    "clothing",
    "B1",
    ["款式描述", "材质比较", "保养咨询"],
    ["sterling silver", "setting", "care instructions"],
  ),
  createScene(
    "cafe-complaint",
    "咖啡店处理错单",
    "Fixing a café order",
    "礼貌指出饮品错误、重申需求并确认重做时间。",
    "dining",
    "B1",
    ["指出错单", "重申需求", "确认时间"],
    ["mixed up", "remake", "right away"],
  ),
  createScene(
    "cooking-class",
    "烹饪课协作",
    "Taking a cooking class",
    "确认步骤、描述食材状态并与搭档分工。",
    "dining",
    "B1",
    ["步骤确认", "状态描述", "任务分工"],
    ["finely chopped", "simmer", "take turns"],
  ),
  createScene(
    "property-inspection",
    "房屋交接检查",
    "Inspecting a rental property",
    "记录房屋现状、指出损坏并确认维修责任。",
    "housing",
    "B2",
    ["现状记录", "损坏说明", "责任确认"],
    ["inspection report", "wear and tear", "repair responsibility"],
  ),
  createScene(
    "tenant-renewal",
    "续租协商",
    "Renewing a lease",
    "讨论新租期、租金变化和续租条件。",
    "housing",
    "B2",
    ["租期讨论", "租金协商", "条件确认"],
    ["renewal", "rent increase", "lease term"],
  ),
  createScene(
    "subway-disruption",
    "地铁停运改道",
    "Handling a subway disruption",
    "了解停运范围、寻找替代路线并估算延误。",
    "transport",
    "B1",
    ["停运确认", "路线替代", "延误估算"],
    ["service disruption", "replacement bus", "delay"],
  ),
  createScene(
    "hotel-shuttle",
    "酒店接驳车",
    "Arranging a hotel shuttle",
    "确认接驳地点、班次和行李空间。",
    "transport",
    "A2",
    ["地点确认", "班次询问", "行李安排"],
    ["pickup point", "shuttle schedule", "luggage space"],
  ),
  createScene(
    "technical-interview",
    "技术面试",
    "Technical interview",
    "澄清题目、讲解方案并分析复杂度取舍。",
    "work",
    "C1",
    ["题目澄清", "方案讲解", "复杂度分析"],
    ["constraint", "trade-off", "time complexity"],
  ),
  createScene(
    "sprint-retrospective",
    "迭代复盘",
    "Sprint retrospective",
    "总结有效做法、分析阻碍并提出流程改进。",
    "work",
    "B2",
    ["经验总结", "阻碍分析", "改进建议"],
    ["went well", "bottleneck", "action item"],
  ),
  createScene(
    "conference-call",
    "跨国电话会议",
    "International conference call",
    "确认音频状态、澄清发言并总结跨时区决定。",
    "work",
    "B2",
    ["音频确认", "发言澄清", "决定总结"],
    ["cutting out", "could you repeat", "recap"],
  ),
  createScene(
    "partners-family",
    "拜访伴侣家人",
    "Meeting a partner's family",
    "得体自我介绍、回应关心并参与家庭话题。",
    "social",
    "B1",
    ["得体介绍", "回应关心", "参与话题"],
    ["lovely to meet you", "settling in", "family tradition"],
  ),
  createScene(
    "neighbor-dispute",
    "邻里分歧协商",
    "Resolving a neighbor dispute",
    "客观说明问题、听取对方立场并约定解决办法。",
    "social",
    "B2",
    ["问题说明", "立场倾听", "方案约定"],
    ["from my side", "understand your concern", "work something out"],
  ),
  createScene(
    "urgent-care",
    "急诊门诊",
    "At urgent care",
    "说明紧急程度、回答分诊问题并确认等待安排。",
    "health",
    "B1",
    ["紧急程度", "分诊问答", "等待安排"],
    ["urgent", "triage", "waiting time"],
  ),
  createScene(
    "physiotherapy",
    "物理治疗",
    "At physical therapy",
    "描述活动受限、确认动作并反馈疼痛程度。",
    "health",
    "B2",
    ["活动受限", "动作确认", "疼痛反馈"],
    ["range of motion", "stretch", "discomfort"],
  ),
  createScene(
    "insurance-claim",
    "保险理赔",
    "Filing an insurance claim",
    "说明事件经过、提交证明并确认理赔进度。",
    "services",
    "B2",
    ["经过说明", "证明提交", "进度确认"],
    ["claim form", "supporting evidence", "settlement"],
  ),
  createScene(
    "parcel-collection",
    "领取包裹",
    "Collecting a parcel",
    "核对取件信息、说明授权并处理异常状态。",
    "services",
    "A2",
    ["信息核对", "授权说明", "异常处理"],
    ["collection code", "authorized person", "delivery status"],
  ),
  createScene(
    "thesis-supervision",
    "论文导师沟通",
    "Thesis supervision",
    "汇报研究进展、讨论论证问题并确认修改优先级。",
    "learning",
    "C1",
    ["进展汇报", "论证讨论", "修改排序"],
    ["research question", "methodology", "revision priority"],
  ),
  createScene(
    "campus-orientation",
    "校园迎新",
    "Campus orientation",
    "询问校园设施、课程注册和社团活动。",
    "learning",
    "A2",
    ["设施问路", "注册咨询", "活动了解"],
    ["student center", "enrollment", "student club"],
  ),
  createScene(
    "severe-weather-alert",
    "极端天气避险",
    "Responding to severe weather",
    "确认预警范围、了解避险地点并协调联络。",
    "emergency",
    "B2",
    ["预警确认", "地点询问", "联络协调"],
    ["weather warning", "shelter", "emergency contact"],
  ),
]

export const sceneItems: SceneItem[] = [...coreSceneItems, ...expandedSceneItems]
